export const types = {
    GET_SAMPLEAPI_SUCCESS : 'GET_SAMPLEAPI_SUCCESS',
    GET_SAMPLEAPI_FAILURE : 'GET_SAMPLEAPI_FAILURE',
    POST_LOGIN_SUCCESS : 'POST_LOGIN_SUCCESS',
    POST_LOGIN_FAILURE : 'POST_LOGIN_FAILURE',
    GET_USERPROFILE_SUCCESS : 'GET_USERPROFILE_SUCCESS',
    GET_USERPROFILE_FAILURE : 'GET_USERPROFILE_FAILURE',
    POST_CREATESTUDENT_SUCCESS : 'POST_CREATESTUDENT_SUCCESS',
    POST_CREATESTUDENT_FAILURE : 'POST_CREATESTUDENT_FAILURE',
    GET_USERLIST_SUCCESS : 'GET_USERLIST_SUCCESS',
    GET_USERLIST_FAILED : 'GET_USERLIST_FAILED',
    PUT_EDITUSERDETAILS_SUCCESS : 'PUT_EDITUSERDETAILS_SUCCESS',
    PUT_EDITUSERDETAILS_FAILURE : 'PUT_EDITUSERDETAILS_FAILURE',
    GET_USERBYID_SUCCESS : 'GET_USERBYID_SUCCESS',
    GET_USERBYID_FAILURE : 'GET_USERBYID_FAILURE',
    GENERATE_CERTIFICATE_SUCCESS : 'GENERATE_CERTIFICATE_SUCCESS',
    GENERATE_CERTIFICATE_FAILED : 'GENERATE_CERTIFICATE_FAILED'
}