export const types = {
    GET_SAMPLEAPI_SUCCESS : 'GET_SAMPLEAPI_SUCCESS',
    GET_SAMPLEAPI_FAILURE : 'GET_SAMPLEAPI_FAILURE',
    POST_LOGIN_SUCCESS : 'POST_LOGIN_SUCCESS',
    POST_LOGIN_FAILURE : 'POST_LOGIN_FAILURE',
    GET_USERPROFILE_SUCCESS : 'GET_USERPROFILE_SUCCESS',
    GET_USERPROFILE_FAILURE : 'GET_USERPROFILE_FAILURE'
}